package com.agencytrip.agencytripapi.infrastructure.adapter.in.web;
import com.agencytrip.agencytripapi.application.dto.Requests; import com.agencytrip.agencytripapi.application.service.UserService; import com.agencytrip.agencytripapi.domain.model.User; import io.swagger.v3.oas.annotations.Operation; import io.swagger.v3.oas.annotations.security.SecurityRequirement; import io.swagger.v3.oas.annotations.tags.Tag; import jakarta.validation.Valid; import java.util.*; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.security.oauth2.jwt.Jwt; import org.springframework.web.bind.annotation.*;
@Tag(name="Usuarios") @RestController @RequestMapping("/api/Usuarios") public class UserController { private final UserService service; public UserController(UserService s){service=s;}
 @Operation(summary="Iniciar sesión",description="Valida credenciales y devuelve un JWT con vigencia de dos horas.") @PostMapping("/login") public Map<String,Object> login(@Valid @RequestBody Requests.Login r){var x=service.login(r);return Map.of("mensaje","Inicio de sesión exitoso.","token",x.token(),"usuario",ApiResponses.userAuth(x.user(),x.role()));}
 @Operation(summary="Consultar perfil autenticado",security=@SecurityRequirement(name="bearerAuth")) @GetMapping("/perfil") public Map<String,Object> profile(@AuthenticationPrincipal Jwt jwt){return Map.of("mensaje","Perfil obtenido correctamente.","usuario",jwt.getSubject(),"correo",jwt.getClaimAsString("email"),"rol",jwt.getClaimAsStringList("roles").getFirst());}
 @Operation(summary="Listar usuarios activos",security=@SecurityRequirement(name="bearerAuth")) @GetMapping @PreAuthorize("hasRole('ADMINISTRADOR')") public List<ApiResponses.UserAdmin> users(){return service.users().stream().map(ApiResponses::userAdmin).toList();}
 @Operation(summary="Actualizar usuario",security=@SecurityRequirement(name="bearerAuth")) @PutMapping("/{id}") @PreAuthorize("hasRole('ADMINISTRADOR')") public Map<String,Object> update(@PathVariable int id,@Valid @RequestBody Requests.UserUpdate r){User u=service.update(id,r);return Map.of("mensaje","Usuario actualizado correctamente.","usuario",ApiResponses.userAdmin(u));}
 @Operation(summary="Desactivar usuario",security=@SecurityRequirement(name="bearerAuth")) @DeleteMapping("/{id}") @PreAuthorize("hasRole('ADMINISTRADOR')") public Map<String,String> disable(@PathVariable int id){service.disable(id);return Map.of("mensaje","Usuario desactivado correctamente.");}
}
