package com.agencytrip.agencytripapi.application.service;
import com.agencytrip.agencytripapi.application.dto.Requests; import com.agencytrip.agencytripapi.domain.model.*; import com.agencytrip.agencytripapi.domain.port.out.TravelRepositoryPort; import java.time.LocalDateTime; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.transaction.annotation.Transactional;
public class PaymentService {
 private final TravelRepositoryPort repo; public PaymentService(TravelRepositoryPort repo){this.repo=repo;}
 public List<Payment> all(){return repo.findPayments();} public List<Payment> byUser(int userId){return repo.findPaymentsByUser(userId);}
 @Transactional public PaymentResult create(int userId,Requests.Payment r){Reservation reservation=repo.findReservation(r.idReserva()).orElseThrow(()->CatalogService.notFound("La reserva no existe."));if(!reservation.getIdUsuario().equals(userId))throw new BusinessException(HttpStatus.FORBIDDEN,"No puede realizar un pago para esta reserva.");if(repo.hasApprovedPayment(r.idReserva()))throw CatalogService.bad("Esta reserva ya tiene un pago aprobado.");String method=r.metodoPago().toUpperCase();if(!Set.of("PSE","TARJETA","TRANSFERENCIA").contains(method))throw CatalogService.bad("Método de pago no válido.");Payment p=new Payment();p.setIdReserva(reservation.getIdReserva());p.setFechaPago(LocalDateTime.now());p.setMonto(reservation.getPrecioTotal());p.setMetodoPago(method);p.setEstado("APROBADO");reservation.setEstado("CONFIRMADA");repo.saveReservation(reservation);return new PaymentResult(repo.savePayment(p),reservation);}
 @Transactional public PaymentResult updateStatus(int id,Requests.PaymentStatus r){Payment p=repo.findPayment(id).orElseThrow(()->CatalogService.notFound("El pago no existe."));String status=r.estado().toUpperCase();if(!Set.of("PENDIENTE","APROBADO","RECHAZADO").contains(status))throw CatalogService.bad("Estado no válido. Use PENDIENTE, APROBADO o RECHAZADO.");p.setEstado(status);Reservation reservation=repo.findReservation(p.getIdReserva()).orElse(null);if(reservation!=null){reservation.setEstado("APROBADO".equals(status)?"CONFIRMADA":"PENDIENTE");repo.saveReservation(reservation);}return new PaymentResult(repo.savePayment(p),reservation);}
 public record PaymentResult(Payment payment,Reservation reservation){}
}
