package com.agencytrip.agencytripapi.application.service;
import com.agencytrip.agencytripapi.application.dto.Requests; import com.agencytrip.agencytripapi.domain.model.*; import com.agencytrip.agencytripapi.domain.port.out.TravelRepositoryPort; import java.math.BigDecimal; import java.time.LocalDateTime; import java.util.*; import org.springframework.transaction.annotation.Transactional;
/** La transacción es aplicada por el adaptador Spring que invoca estos casos de uso. */
public class ReservationService {
 private final TravelRepositoryPort repo; public ReservationService(TravelRepositoryPort repo){this.repo=repo;}
 public List<Reservation> all(){return repo.findReservations();} public List<Reservation> byUser(int id){return repo.findReservationsByUser(id);}
 @Transactional public Reservation create(int userId,Requests.Reservation r){PackageTrip p=repo.findPackage(r.idPaquete()).filter(PackageTrip::isEstado).orElseThrow(()->CatalogService.notFound("El paquete no existe o no está disponible."));if(r.cantidadPersonas()>p.getCupos())throw CatalogService.bad("No hay suficientes cupos disponibles.");Reservation reservation=new Reservation();reservation.setIdUsuario(userId);reservation.setIdPaquete(p.getIdPaquete());reservation.setFechaReserva(LocalDateTime.now());reservation.setCantidadPersonas(r.cantidadPersonas());reservation.setPrecioTotal(p.getPrecio().multiply(BigDecimal.valueOf(r.cantidadPersonas())));reservation.setEstado("PENDIENTE");p.setCupos(p.getCupos()-r.cantidadPersonas());repo.savePackage(p);return repo.saveReservation(reservation);}
 @Transactional public Reservation changeStatus(int id,Requests.ReservationStatus r){Reservation reservation=repo.findReservation(id).orElseThrow(()->CatalogService.notFound("La reserva no existe."));String status=r.estado().toUpperCase();if(!Set.of("PENDIENTE","CONFIRMADA","CANCELADA").contains(status))throw CatalogService.bad("Estado no válido.");if("CANCELADA".equals(status)&&"CANCELADA".equals(reservation.getEstado()))throw CatalogService.bad("La reserva ya está cancelada.");if("CANCELADA".equals(status)){PackageTrip p=repo.findPackage(reservation.getIdPaquete()).orElseThrow(()->CatalogService.bad("No se pudo obtener el paquete asociado."));p.setCupos(p.getCupos()+reservation.getCantidadPersonas());repo.savePackage(p);}reservation.setEstado(status);return repo.saveReservation(reservation);}
}
