package com.agencytrip.agencytripapi.infrastructure.config;
import java.nio.charset.StandardCharsets; import javax.crypto.SecretKey; import javax.crypto.spec.SecretKeySpec; import com.nimbusds.jose.proc.SecurityContext; import org.springframework.core.convert.converter.Converter;
import org.springframework.beans.factory.annotation.Value; import org.springframework.context.annotation.*; import org.springframework.http.HttpMethod; import org.springframework.security.config.Customizer; import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity; import org.springframework.security.config.annotation.web.builders.HttpSecurity; import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity; import org.springframework.security.config.http.SessionCreationPolicy; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.security.oauth2.core.*; import org.springframework.security.oauth2.jwt.*; import org.springframework.security.oauth2.server.resource.authentication.*; import org.springframework.security.web.SecurityFilterChain; import org.springframework.web.cors.*;
@Configuration @EnableWebSecurity @EnableMethodSecurity
public class SecurityConfig {
 @Bean PasswordEncoder passwordEncoder(){return new BCryptPasswordEncoder();}
 @Bean SecretKey jwtKey(@Value("${agencytrip.jwt.secret}") String secret){if(secret==null||secret.length()<32)throw new IllegalStateException("JWT_SECRET debe configurarse con al menos 32 caracteres.");return new SecretKeySpec(secret.getBytes(StandardCharsets.UTF_8),"HmacSHA256");}
 @Bean JwtDecoder jwtDecoder(SecretKey key,@Value("${agencytrip.jwt.issuer}") String issuer,@Value("${agencytrip.jwt.audience}") String audience){NimbusJwtDecoder decoder=NimbusJwtDecoder.withSecretKey(key).build();OAuth2TokenValidator<Jwt> audienceValidator=jwt->jwt.getAudience().contains(audience)?OAuth2TokenValidatorResult.success():OAuth2TokenValidatorResult.failure(new OAuth2Error("invalid_token","La audiencia del token no es válida.",null));decoder.setJwtValidator(new DelegatingOAuth2TokenValidator<>(JwtValidators.createDefaultWithIssuer(issuer),audienceValidator));return decoder;}
 @Bean JwtEncoder jwtEncoder(SecretKey key){return new NimbusJwtEncoder(new com.nimbusds.jose.jwk.source.ImmutableSecret<SecurityContext>(key));}
 @Bean SecurityFilterChain filterChain(HttpSecurity http,JwtDecoder decoder,JwtAuthenticationConverter converter)throws Exception{return http.csrf(csrf->csrf.disable()).cors(Customizer.withDefaults()).sessionManagement(s->s.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).authorizeHttpRequests(a->a.requestMatchers(HttpMethod.POST,"/api/Registro","/api/Usuarios/login").permitAll().requestMatchers(HttpMethod.GET,"/api/Destinos","/api/Paquetes","/api/Hoteles","/api/Transportes").permitAll().requestMatchers("/api/Admin/**","/api/Roles/**").hasRole("ADMINISTRADOR").anyRequest().authenticated()).oauth2ResourceServer(o->o.jwt(j->j.decoder(decoder).jwtAuthenticationConverter(converter))).build();}
 @Bean JwtAuthenticationConverter jwtAuthenticationConverter(){JwtGrantedAuthoritiesConverter roles=new JwtGrantedAuthoritiesConverter();roles.setAuthoritiesClaimName("roles");roles.setAuthorityPrefix("ROLE_");JwtAuthenticationConverter converter=new JwtAuthenticationConverter();converter.setJwtGrantedAuthoritiesConverter(roles);return converter;}
 @Bean CorsConfigurationSource corsConfigurationSource(){CorsConfiguration c=new CorsConfiguration();c.addAllowedOrigin("http://localhost:4200");c.addAllowedHeader("*");c.addAllowedMethod("*");UrlBasedCorsConfigurationSource s=new UrlBasedCorsConfigurationSource();s.registerCorsConfiguration("/**",c);return s;}
}
